### ISSUE TITLE
Update Changelog.md

### ISSUE THREAD

**Issue by acowley** [haskell-works/hw-dsv#106]
This is a super minor note, but I'd like to ask that the changelog be updated on major version bumps. As a maintainer of a downstream package, it would make it easier for me to deal with upper-bounds, and serve as a reference for changes that I need to act on.

**Comment by newhoggy** [comment]
Looks like I needed up bump the upper bound of `hw-ip`.

**Comment by newhoggy** [comment]
I updated the upper bound of `hw-ip` to `2.5`

**Comment by newhoggy** [comment]
Update cabal metadata too.

Building on stackage: https://github.com/commercialhaskell/stackage/pull/5069

**Comment by newhoggy** [comment]
`ChangeLog.md` has been updated.  Thanks for the feedback.
